#!/bin/bash

function check_env_file_exists {
    # Check if .env file exists
    if [ ! -f .env ]; then
        echo ".env file not found"
        exit 1
    fi
}

function unset_env_variables {
    # Read .env file
    while read -r line || [[ -n "$line" ]]; do
        # Skip the line if it starts with a # (considered as comments)
        if [[ $line = \#* ]]; then
            continue
        fi
        # Skip the line if it is empty
        if [[ $line = "" ]]; then
            continue
        fi
        # Get the variable name (everything before the = sign)
        varname=$(echo "$line" | cut -d '=' -f 1)
        # Unset the variable
        unset $varname
    done < ".env"
}

function set_env_variables {
    # Read .env file
    while read -r line || [[ -n "$line" ]]; do
        # Skip the line if it starts with a # (considered as comments)
        if [[ $line = \#* ]]; then
            continue
        fi
        # Skip the line if it is empty
        if [[ $line = "" ]]; then
            continue
        fi
        # Export environment variable
        export "$line"
    done < ".env"
}

# Call functions
check_env_file_exists
set_env_variables
make ssh_upload
unset_env_variables
